const europaFixtures = 'https://www.uefa.com/uefaeuropaleague/news/02a8-2174cafa5bb6-82bbc20c9b92-1000--2026-27-europa-league-all-the-league-phase-fixtures/'
const conferenceFixtures = 'https://www.uefa.com/uefaconferenceleague/news/02a8-2174cb200f25-b94693ddff4e-1000--2026-27-conference-league-all-the-league-phase-fixtures/'
const uefaSanctions = 'https://www.uefa.com/running-competitions/disciplinary/stadium-bans/'

function uelPhase(id, phase, startDate, endDate = startDate, note) {
  return {
    _id: `starter-competition-uel-${id}`,
    name: 'UEFA Europa League',
    shortName: 'EUROPA LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase,
    startDate,
    endDate,
    status: 'confirmed',
    ...(note ? {note} : {}),
    sourceUrls: [europaFixtures],
  }
}

export const europaLeagueCompetitions = [
  uelPhase('md2-2026', 'Ligaphase · Spieltag 2', '2026-10-15'),
  uelPhase('md3-2026', 'Ligaphase · Spieltag 3', '2026-10-22'),
  uelPhase('md4-2026', 'Ligaphase · Spieltag 4', '2026-11-05'),
  uelPhase('md5-2026', 'Ligaphase · Spieltag 5', '2026-11-26'),
  uelPhase('md6-2026', 'Ligaphase · Spieltag 6', '2026-12-10'),
  uelPhase('md7-2027', 'Ligaphase · Spieltag 7', '2027-01-21'),
  uelPhase('md8-2027', 'Ligaphase · Spieltag 8', '2027-01-28', '2027-01-28', 'Letzter Spieltag der Ligaphase 2026/27.'),
]

export const europaConferenceMatches = [
  {
    _id: 'uel-watch-besiktas-marseille-2026-09-17',
    homeTeam: 'Beşiktaş',
    awayTeam: 'Olympique Marseille',
    country: 'Türkei',
    region: 'europe',
    city: 'Istanbul',
    stadium: 'Tüpraş Stadyumu',
    dateStatus: 'confirmed',
    matchDate: '2026-09-17',
    kickoffTime: '22:00',
    categories: ['fanszene', 'rivalitaet', 'anlass'],
    priority: 2,
    shortDescription: 'Auf dem Papier ein Top-Spiel für Fanszenen – aktuell aber mit dickem Sternchen: Marseille führt bei der UEFA eine aktive Ein-Spiel-Sperre für Auswärtsfans.',
    background: 'Beşiktaş gegen Marseille hätte ohne Einschränkungen Top-Fünf-Potenzial. Wegen der aktuell aktiven UEFA-Sanktion gegen Marseille ist das Spiel zunächst vor allem als Risikohinweis im Kalender.',
    confirmedInfo: 'Termin bestätigt. UEFA listet aktuell eine Sperre für Marseilles Auswärtsfans für ein Spiel; vor Buchung unbedingt erneut prüfen.',
    editorialAssessment: 'Beobachtungsliste mit großem Fragezeichen wegen Gästefansperre.',
    awayFans: 'banned',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures, uefaSanctions],
  },
  {
    _id: 'uel-tip-crystal-palace-lech-2026-09-17',
    homeTeam: 'Crystal Palace',
    awayTeam: 'Lech Poznań',
    country: 'England',
    region: 'europe',
    city: 'London',
    stadium: 'Selhurst Park',
    dateStatus: 'confirmed',
    matchDate: '2026-09-17',
    kickoffTime: '20:00',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 2,
    shortDescription: 'Kompakter englischer Ground, aktive Palace-Heimseite und Lech mit einer der größten polnischen Fanszenen. Keine alte Feindschaft nötig, um das interessant zu finden.',
    background: 'Der Reiz liegt in der Kombination Selhurst Park plus reisestarker Lech-Anhang. Eine besondere direkte Rivalität ist nicht bekannt.',
    confirmedInfo: 'Termin bestätigt; 20:00 Uhr ist die Ortszeit in London.',
    editorialAssessment: 'Hopper-Empfehlung: 8/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uecl-tip-lugano-zvezda-2026-10-15',
    homeTeam: 'FC Lugano',
    awayTeam: 'Crvena Zvezda',
    country: 'Schweiz',
    region: 'europe',
    city: 'Lugano',
    dateStatus: 'confirmed',
    matchDate: '2026-10-15',
    kickoffTime: '18:45',
    categories: ['fanszene', 'auswaertsfahrt', 'unter_dem_radar'],
    priority: 2,
    shortDescription: 'Roter Stern in der Schweiz ist wegen der serbischen Diaspora ohnehin interessant. Dazu kommt ein vergleichsweise kleiner Gastgeber – starkes Potenzial für viel Zvezda im Stadtbild.',
    background: 'Bei Young Boys versammelten sich 2023 rund 2.000 Zvezda-Anhänger vor dem Spiel in Bern. Für Lugano bleibt die konkrete Mobilisierung noch abzuwarten.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uecl-tip-hajduk-ajax-2026-10-15',
    homeTeam: 'Hajduk Split',
    awayTeam: 'Ajax',
    country: 'Kroatien',
    region: 'europe',
    city: 'Split',
    stadium: 'Stadion Poljud',
    dateStatus: 'confirmed',
    matchDate: '2026-10-15',
    kickoffTime: '18:45',
    categories: ['fanszene', 'anlass'],
    priority: 2,
    shortDescription: 'Torcida, Poljud und Ajax – dazu das erste Pflichtspiel beider Klubs seit den 1990ern. Keine belastbare moderne Feindschaft, aber eine ziemlich starke Kombination.',
    background: 'Hajduk und Ajax trafen Anfang/Mitte der 1990er im Europapokal aufeinander. Nach mehr als drei Jahrzehnten kommt Ajax wieder nach Split.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uecl-watch-kups-trabzonspor-2026-10-15',
    homeTeam: 'KuPS Kuopio',
    awayTeam: 'Trabzonspor',
    country: 'Finnland',
    region: 'europe',
    city: 'Kuopio',
    dateStatus: 'confirmed',
    matchDate: '2026-10-15',
    kickoffTime: '19:45',
    categories: ['auswaertsfahrt', 'unter_dem_radar'],
    priority: 1,
    shortDescription: 'Als Reise eigentlich herrlich schräg: Trabzonspor in Kuopio. Aktuell steht dem aber eine aktive UEFA-Sperre für Trabzonspors Auswärtsfans entgegen.',
    background: 'Die Partie wäre wegen Spielort und türkischem Reise-Potenzial interessant. Derzeit ist sie vor allem ein Beispiel dafür, warum Gästefan-Sanktionen vor jeder Buchung geprüft werden müssen.',
    confirmedInfo: 'Termin bestätigt. UEFA listet Trabzonspor aktuell mit einer Ein-Spiel-Sperre für Auswärtsfans.',
    editorialAssessment: 'Beobachtungsliste – aktuell keine normale Gästefahrt.',
    awayFans: 'banned',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures, uefaSanctions],
  },
  {
    _id: 'uecl-tip-panathinaikos-borac-2026-10-15',
    homeTeam: 'Panathinaikos',
    awayTeam: 'Borac Banja Luka',
    country: 'Griechenland',
    region: 'europe',
    city: 'Athen',
    dateStatus: 'confirmed',
    matchDate: '2026-10-15',
    kickoffTime: '19:45',
    categories: ['fanszene', 'rivalitaet'],
    priority: 3,
    shortDescription: 'Beim Duell 2024 in Banja Luka provozierten Panathinaikos-Fans mit „Dinamo Zagreb“-Rufen. Zwei Jahre später kommt Borac nach Athen – klare Vorgeschichte.',
    background: 'Gate 13 pflegt Kontakte zu Dinamo Zagrebs Bad Blue Boys. Genau diese Verbindung wurde 2024 beim ersten Duell in Banja Luka als Provokation sichtbar.',
    confirmedInfo: 'Termin bestätigt; 19:45 Uhr ist die Ortszeit in Athen.',
    editorialAssessment: 'Hopper-Empfehlung: 9,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uel-tip-marseille-olympiacos-2026-10-15',
    homeTeam: 'Olympique Marseille',
    awayTeam: 'Olympiacos',
    country: 'Frankreich',
    region: 'europe',
    city: 'Marseille',
    stadium: 'Orange Vélodrome',
    dateStatus: 'confirmed',
    matchDate: '2026-10-15',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet'],
    priority: 3,
    shortDescription: 'Marseilles enge Freundschaft mit AEK trifft auf Olympiacos. Bereits 2011 spielte diese Verbindung bei Zwischenfällen rund um das direkte Duell eine Rolle.',
    background: 'Zwischen dem Commando Ultra ’84 und AEKs Original 21 besteht eine langjährige Freundschaft. Beim Olympiacos–OM-Duell 2011 war diese Verbindung bereits Teil der Fan-Vorgeschichte.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 10/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uel-watch-hoffenheim-besiktas-2026-10-15',
    homeTeam: 'TSG Hoffenheim',
    awayTeam: 'Beşiktaş',
    country: 'Deutschland',
    region: 'europe',
    city: 'Sinsheim',
    stadium: 'PreZero Arena',
    dateStatus: 'confirmed',
    matchDate: '2026-10-15',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 1,
    shortDescription: 'Beşiktaş in Sinsheim könnte durch die große türkische Community in Deutschland deutlich mehr Auswärtscharakter bekommen, als die Paarung zunächst vermuten lässt.',
    background: 'Entscheidend werden Gästekontingent und Ticketregeln. Eine besondere direkte Rivalität ist nicht bekannt.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uecl-tip-zvezda-copenhagen-2026-10-22',
    homeTeam: 'Crvena Zvezda',
    awayTeam: 'FC Kopenhagen',
    country: 'Serbien',
    region: 'europe',
    city: 'Belgrad',
    stadium: 'Stadion Rajko Mitić',
    dateStatus: 'confirmed',
    matchDate: '2026-10-22',
    kickoffTime: '18:45',
    categories: ['fanszene', 'anlass'],
    priority: 2,
    shortDescription: 'Beide kennen sich aus der Champions-League-Qualifikation 2019. Sektion 12 im Rajko Mitić gegen die Delije ist auch ohne große Feindschaft eine starke Kombination.',
    background: '2019 sahen mehr als 40.000 das Hinspiel in Belgrad; FCK organisierte das Rückspiel in Kopenhagen mit klarer Fantrennung. Nun folgt das nächste Kapitel.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uecl-watch-trabzonspor-hearts-2026-10-22',
    homeTeam: 'Trabzonspor',
    awayTeam: 'Heart of Midlothian',
    country: 'Türkei',
    region: 'europe',
    city: 'Trabzon',
    dateStatus: 'confirmed',
    matchDate: '2026-10-22',
    kickoffTime: '19:45',
    categories: ['fanszene', 'auswaertsfahrt', 'unter_dem_radar'],
    priority: 1,
    shortDescription: 'Schottischer Auswärtsanhang am Schwarzen Meer: keine große gemeinsame Geschichte, aber eine Reise, die Hearts nicht jedes Jahr angeboten bekommt.',
    background: 'Der Reiz liegt klar in der ungewöhnlichen Auswärtsfahrt und den beiden unterschiedlichen Fußballkulturen.',
    confirmedInfo: 'Termin bestätigt; 19:45 Uhr ist die Ortszeit in Trabzon.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uecl-watch-thun-hajduk-2026-10-22',
    homeTeam: 'FC Thun',
    awayTeam: 'Hajduk Split',
    country: 'Schweiz',
    region: 'europe',
    city: 'Thun',
    stadium: 'Stockhorn Arena',
    dateStatus: 'confirmed',
    matchDate: '2026-10-22',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt', 'unter_dem_radar'],
    priority: 1,
    shortDescription: 'Hajduk in einem vergleichsweise kleinen Schweizer Ground ist grundsätzlich spannend. Ob daraus ein besonders großer Gästeanteil wird, hängt vom Kontingent ab.',
    background: 'In der Schweiz gibt es seit Jahren organisierte kroatische und Hajduk-Strukturen. Die konkrete Mobilisierung für Thun ist aber noch offen.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uel-tip-lech-sunderland-2026-10-22',
    homeTeam: 'Lech Poznań',
    awayTeam: 'Sunderland',
    country: 'Polen',
    region: 'europe',
    city: 'Poznań',
    stadium: 'Enea Stadion',
    dateStatus: 'confirmed',
    matchDate: '2026-10-22',
    kickoffTime: '18:45',
    categories: ['fanszene', 'auswaertsfahrt', 'anlass'],
    priority: 2,
    shortDescription: 'Sunderland ist nach mehr als fünf Jahrzehnten wieder europäisch unterwegs und bekommt direkt Poznań. Große polnische Szene trifft auf einen hochmotivierten englischen Auswärtsanhang.',
    background: 'Lech gehört zu den größten Heimkulissen Polens. Sunderland erlebt die erste Europapokalsaison seit 53 Jahren – entsprechend besonders dürften die Auswärtsreisen behandelt werden.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uecl-watch-freiburg-panathinaikos-2026-12-10',
    homeTeam: 'SC Freiburg',
    awayTeam: 'Panathinaikos',
    country: 'Deutschland',
    region: 'europe',
    city: 'Freiburg',
    stadium: 'Europa-Park Stadion',
    dateStatus: 'confirmed',
    matchDate: '2026-12-10',
    kickoffTime: '18:45',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 1,
    shortDescription: 'Gate 13 in Deutschland ist grundsätzlich einen Blick wert. Eine besondere Freiburg-Panathinaikos-Geschichte ist bislang allerdings nicht bekannt.',
    background: 'Die Partie landet wegen der reisefreudigen Athener Fanszene auf der Beobachtungsliste, nicht wegen einer belegten Rivalität.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uel-watch-omonia-celtic-2026-12-10',
    homeTeam: 'Omonia Nikosia',
    awayTeam: 'Celtic',
    country: 'Zypern',
    region: 'europe',
    city: 'Nikosia',
    stadium: 'GSP-Stadion',
    dateStatus: 'confirmed',
    matchDate: '2026-12-10',
    kickoffTime: '19:45',
    categories: ['fanszene', 'anlass'],
    priority: 1,
    shortDescription: 'Historisch gab es Kontakte zwischen Celtics Green Brigade und Gate 9. Heute gehört dazu ein großes Sternchen, weil Gate 9 die Omonia-Fußballabteilung seit 2018 nicht mehr unterstützt.',
    background: 'Die alten persönlichen Kontakte machen die Partie interessant, sollten aber nicht als aktuelle offizielle Fanfreundschaft zwischen Omonia und Celtic verkauft werden.',
    confirmedInfo: 'Termin bestätigt; 19:45 Uhr ist die Ortszeit in Nikosia.',
    editorialAssessment: 'Beobachtungsliste mit historischem Fanfreundschafts-Kontext.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uecl-tip-stvv-ajax-2026-12-10',
    homeTeam: 'Sint-Truidense VV',
    awayTeam: 'Ajax',
    country: 'Belgien',
    region: 'europe',
    city: 'Sint-Truiden',
    stadium: 'Stayen',
    dateStatus: 'confirmed',
    matchDate: '2026-12-10',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt', 'anlass'],
    priority: 2,
    shortDescription: 'Ajax praktisch über die Grenze bei einem Klub, für den diese Europapokalsaison selbst etwas Besonderes ist. Kurzer Weg und entsprechend hohes Gäste-Potenzial.',
    background: 'Keine große Hassgeschichte – der Reiz liegt in der Nachbarschaft, dem kleinen belgischen Spielort und einer erwartbar starken Ajax-Nachfrage.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uel-tip-milan-sunderland-2026-12-10',
    homeTeam: 'AC Milan',
    awayTeam: 'Sunderland',
    country: 'Italien',
    region: 'europe',
    city: 'Mailand',
    stadium: 'Stadio San Siro',
    dateStatus: 'confirmed',
    matchDate: '2026-12-10',
    kickoffTime: '21:00',
    categories: ['auswaertsfahrt', 'anlass'],
    priority: 1,
    shortDescription: 'Sunderland nach 53 Jahren Europapokal-Abstinenz direkt im San Siro. Der Gästeblock dürfte hier deutlich interessanter sein als der übliche Mailänder Europa-Tourismus.',
    background: 'Für viele Sunderland-Anhänger ist diese Saison die erste echte Europatour ihres Erwachsenenlebens. Genau davon lebt die Empfehlung.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 7,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uel-tip-lech-ferencvaros-2026-12-10',
    homeTeam: 'Lech Poznań',
    awayTeam: 'Ferencváros',
    country: 'Polen',
    region: 'europe',
    city: 'Poznań',
    stadium: 'Enea Stadion',
    dateStatus: 'confirmed',
    matchDate: '2026-12-10',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet'],
    priority: 3,
    shortDescription: 'Ferencváros kommt als enger Freund von Śląsk Wrocław zu einem großen Rivalen der Wrocławer Szene. Keine klassische direkte Feindschaft, aber reichlich Fanpolitik über Bande.',
    background: 'Die Freundschaft zwischen Ferencváros und Śląsk ist weiterhin aktiv. Weil Lech und Śląsk rivalisieren, bekommt das Los zusätzlichen Szenekontext.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 9/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uecl-tip-zvezda-trabzonspor-2026-12-17',
    homeTeam: 'Crvena Zvezda',
    awayTeam: 'Trabzonspor',
    country: 'Serbien',
    region: 'europe',
    city: 'Belgrad',
    stadium: 'Stadion Rajko Mitić',
    dateStatus: 'confirmed',
    matchDate: '2026-12-17',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet'],
    priority: 3,
    shortDescription: '2022 gab es bei beiden direkten Europa-League-Duellen Provokationen und auffällige Kurvenaktionen. Vier Jahre später folgt in Belgrad das nächste Kapitel.',
    background: 'Beim Rückspiel 2022 in Belgrad provozierten sich beide Seiten, die Delije reagierten unter anderem mit einer martialischen Choreografie. Direkte Vorgeschichte ist also vorhanden.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 9/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [conferenceFixtures],
  },
  {
    _id: 'uel-tip-celtic-marseille-2027-01-21',
    homeTeam: 'Celtic',
    awayTeam: 'Olympique Marseille',
    country: 'Schottland',
    region: 'europe',
    city: 'Glasgow',
    stadium: 'Celtic Park',
    dateStatus: 'confirmed',
    matchDate: '2027-01-21',
    kickoffTime: '20:00',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 2,
    shortDescription: 'Celtic Park plus Marseille: keine belastbare große Fanfeindschaft, dafür zwei Kurven, die aus einem Europapokalabend ziemlich viel machen können.',
    background: 'Die Empfehlung lebt von Heim- und Gästeszene, nicht von einer erfundenen Rivalität.',
    confirmedInfo: 'Termin bestätigt; 20:00 Uhr ist die Ortszeit in Glasgow.',
    editorialAssessment: 'Hopper-Empfehlung: 8/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uel-tip-marseille-anderlecht-2027-01-28',
    homeTeam: 'Olympique Marseille',
    awayTeam: 'RSC Anderlecht',
    country: 'Frankreich',
    region: 'europe',
    city: 'Marseille',
    stadium: 'Orange Vélodrome',
    dateStatus: 'confirmed',
    matchDate: '2027-01-28',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet', 'auswaertsfahrt'],
    priority: 3,
    shortDescription: 'Die Mauves Army pflegt enge Kontakte zu Lyon 1950 – und Lyon ist für Marseille nun wirklich kein neutraler Name. Interessante Rivalität über Bande.',
    background: 'Eine jahrzehntelange direkte OM–Anderlecht-Feindschaft wäre übertrieben. Die Verbindung der Anderlechter Szene nach Lyon gibt dem Spiel aber einen konkreten zusätzlichen Reiz.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 9/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
  {
    _id: 'uel-tip-omonia-besiktas-2027-01-28',
    homeTeam: 'Omonia Nikosia',
    awayTeam: 'Beşiktaş',
    country: 'Zypern',
    region: 'europe',
    city: 'Nikosia',
    stadium: 'GSP-Stadion',
    dateStatus: 'confirmed',
    matchDate: '2027-01-28',
    kickoffTime: '22:00',
    categories: ['fanszene', 'anlass'],
    priority: 3,
    shortDescription: 'Historisch außergewöhnlich: Beşiktaş soll erstmals ein Pflichtspiel auf Zypern bestreiten. Politischer Unterbau ja – automatische Hasspartie daraus basteln nein.',
    background: '1986 hätte Beşiktaş bereits gegen APOEL in Nikosia spielen sollen; das Duell fand wegen des politischen Konflikts nicht statt. Vier Jahrzehnte später steht nun Omonia auf dem Spielplan.',
    confirmedInfo: 'Termin bestätigt; 22:00 Uhr ist die Ortszeit in Nikosia.',
    editorialAssessment: 'Hopper-Empfehlung: 9,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    sourceUrls: [europaFixtures],
  },
]
