const uefaFixtures = 'https://www.uefa.com/uefachampionsleague/news/02a8-2174c9e9019d-f909a77bd77a-1000--2026-27-champions-league-all-the-league-phase-fixtures/'
const articleUrl = 'https://tandemhopper.de/geschichten/champions-league-fuer-groundhopper'
const article = {title: 'Champions League für Groundhopper', slug: 'champions-league-fuer-groundhopper'}

export const championsLeagueCompetitions = [
  {
    _id: 'starter-competition-ucl-md2-2026',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 2',
    startDate: '2026-10-13',
    endDate: '2026-10-14',
    status: 'confirmed',
    note: 'Zweiter Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
  {
    _id: 'starter-competition-ucl-md3-2026',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 3',
    startDate: '2026-10-20',
    endDate: '2026-10-21',
    status: 'confirmed',
    note: 'Dritter Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
  {
    _id: 'starter-competition-ucl-md4-2026',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 4',
    startDate: '2026-11-03',
    endDate: '2026-11-04',
    status: 'confirmed',
    note: 'Vierter Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
  {
    _id: 'starter-competition-ucl-md5-2026',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 5',
    startDate: '2026-11-24',
    endDate: '2026-11-25',
    status: 'confirmed',
    note: 'Fünfter Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
  {
    _id: 'starter-competition-ucl-md6-2026',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 6',
    startDate: '2026-12-08',
    endDate: '2026-12-09',
    status: 'confirmed',
    note: 'Sechster Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
  {
    _id: 'starter-competition-ucl-md7-2027',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 7',
    startDate: '2027-01-19',
    endDate: '2027-01-20',
    status: 'confirmed',
    note: 'Siebter Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
  {
    _id: 'starter-competition-ucl-md8-2027',
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 8',
    startDate: '2027-01-27',
    endDate: '2027-01-27',
    status: 'confirmed',
    note: 'Letzter Spieltag der Ligaphase 2026/27.',
    sourceUrls: [uefaFixtures],
  },
]

export const championsLeagueMatches = [
  {
    _id: 'ucl-tip-slavia-lens-2026-09-10',
    homeTeam: 'Slavia Prag',
    awayTeam: 'RC Lens',
    country: 'Tschechien',
    region: 'europe',
    city: 'Prag',
    stadium: 'Fortuna Arena',
    dateStatus: 'confirmed',
    matchDate: '2026-09-10',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt', 'anlass'],
    priority: 2,
    shortDescription: 'Lens hat zuletzt auch weit entfernte Europapokal-Gästeblöcke gefüllt, Slavia bringt selbst eine aktive Kurve mit. Keine große Vorgeschichte – aber ein ziemlich guter Auftakt für Fanszenen-Beobachter.',
    background: 'Lens reist stark, Prag ist gut erreichbar und Slavia verfügt über eine aktive Heimkurve. Für beide Vereine ist Champions League außerdem kein jährlicher Normalzustand.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 7/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-slovan-stuttgart-2026-10-14',
    homeTeam: 'Slovan Bratislava',
    awayTeam: 'VfB Stuttgart',
    country: 'Slowakei',
    region: 'europe',
    city: 'Bratislava',
    stadium: 'Tehelné pole',
    dateStatus: 'confirmed',
    matchDate: '2026-10-14',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet', 'auswaertsfahrt'],
    priority: 3,
    shortDescription: 'Kurzer Weg für Stuttgart, alte Vorgeschichte aus dem Europa-League-Play-off 2010 und ein derzeit sehr reisefreudiger VfB-Anhang. Einer der klaren Tipps der Ligaphase.',
    background: '2010 kam es rund um Slovan – Stuttgart zu Zwischenfällen und einem Durchbruchsversuch aus dem Slovan-Bereich. Dazu ist Bratislava für Stuttgarter vergleichsweise einfach erreichbar.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 9/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-fenerbahce-slavia-2026-10-20',
    homeTeam: 'Fenerbahçe',
    awayTeam: 'Slavia Prag',
    country: 'Türkei',
    region: 'europe',
    city: 'Istanbul',
    stadium: 'Şükrü Saracoğlu Stadyumu',
    dateStatus: 'confirmed',
    matchDate: '2026-10-20',
    kickoffTime: '19:45',
    categories: ['fanszene', 'rivalitaet'],
    priority: 3,
    shortDescription: '2022 Ärger in Istanbul, 2024 neuer Szene-Stoff – und jetzt geht es wieder nach Kadıköy. Eines der Spiele mit der klarsten direkten Vorgeschichte.',
    background: 'Nach dem Duell 2022 bestätigte Slavia einen verletzten Anhänger in Istanbul. Beim erneuten Treffen 2024 kursierten aus der Szene Meldungen über erbeutetes Fenerbahçe-Material.',
    confirmedInfo: 'Termin ist bestätigt; 19:45 Uhr ist die Ortszeit in Istanbul.',
    editorialAssessment: 'Hopper-Empfehlung: 9,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-watch-lille-galatasaray-2026-10-21',
    homeTeam: 'Lille OSC',
    awayTeam: 'Galatasaray',
    country: 'Frankreich',
    region: 'europe',
    city: 'Lille',
    stadium: 'Stade Pierre-Mauroy',
    dateStatus: 'confirmed',
    matchDate: '2026-10-21',
    kickoffTime: '18:45',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 1,
    shortDescription: 'Lille liegt für die große Galatasaray-Diaspora in Deutschland, Frankreich, Belgien und den Niederlanden ziemlich günstig. Direkte Rivalität: keine. Gäste-Potenzial: ordentlich.',
    background: 'Frühere Galatasaray-Auswärtsspiele in Westeuropa zeigen, wie stark der Klub auch außerhalb Istanbuls mobilisieren kann. Deshalb bleibt Lille auf unserer Beobachtungsliste.',
    confirmedInfo: 'Termin und Anstoßzeit sind bestätigt.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, 'https://www.galatasaray.org/haber/futbol/sampiyonlar-ligi/galatasarayin-sampiyonlar-ligi-rakipleri-belli-oldu/60827', articleUrl],
  },
  {
    _id: 'ucl-tip-club-brugge-lens-2026-10-21',
    homeTeam: 'Club Brugge',
    awayTeam: 'RC Lens',
    country: 'Belgien',
    region: 'europe',
    city: 'Brügge',
    stadium: 'Jan Breydelstadion',
    dateStatus: 'confirmed',
    matchDate: '2026-10-21',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet', 'auswaertsfahrt'],
    priority: 3,
    shortDescription: 'Kurzer Grenztrip, reisestarker Lens-Anhang und die Verbindung von Teilen der Brugge-Szene zum Lens-Rivalen Lille. Auf dem Papier unscheinbar, aus Fansicht ganz weit oben.',
    background: 'Beim eskalierten Derby Lens – Lille 2021 wurden Club-Brugge-Anhänger im Lille-Gästebereich festgestellt. Dazu ist Brügge für Lens eine der kürzesten internationalen Auswärtsfahrten.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 10/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-galatasaray-stuttgart-2026-11-03',
    homeTeam: 'Galatasaray',
    awayTeam: 'VfB Stuttgart',
    country: 'Türkei',
    region: 'europe',
    city: 'Istanbul',
    stadium: 'RAMS Park',
    dateStatus: 'confirmed',
    matchDate: '2026-11-03',
    kickoffTime: '20:45',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 2,
    shortDescription: 'Galatasaray zuhause plus ein VfB, dessen Führung selbst mit tausenden Stuttgartern in Istanbul rechnet. Kein historisches Hassspiel – aber starkes Potenzial für einen großen Gästemob.',
    background: 'Die Empfehlung lebt vor allem von der erwartbaren Stuttgarter Mobilisierung und der Galatasaray-Heimkurve, nicht von einer belegten direkten Rivalität.',
    confirmedInfo: 'Termin ist bestätigt; 20:45 Uhr ist die Ortszeit in Istanbul.',
    editorialAssessment: 'Hopper-Empfehlung: 8/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, 'https://www.galatasaray.org/haber/futbol/sampiyonlar-ligi/galatasarayin-sampiyonlar-ligi-rakipleri-belli-oldu/60827', articleUrl],
  },
  {
    _id: 'ucl-watch-lask-slovan-2026-11-03',
    homeTeam: 'LASK',
    awayTeam: 'Slovan Bratislava',
    country: 'Österreich',
    region: 'europe',
    city: 'Linz',
    stadium: 'Raiffeisen Arena',
    dateStatus: 'confirmed',
    matchDate: '2026-11-03',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt', 'unter_dem_radar'],
    priority: 1,
    shortDescription: 'Kurze Strecke zwischen Bratislava und Linz, kleine Arena und zwei aktive Szenen. Keine besondere gemeinsame Vorgeschichte bekannt – geografisch aber ziemlich interessant.',
    background: 'Das Spiel bleibt vor allem wegen Entfernung und Rahmenbedingungen auf der Beobachtungsliste. Eine direkte Fanfeindschaft ist nicht belegt.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-psv-club-brugge-2026-11-04',
    homeTeam: 'PSV Eindhoven',
    awayTeam: 'Club Brugge',
    country: 'Niederlande',
    region: 'europe',
    city: 'Eindhoven',
    stadium: 'Philips Stadion',
    dateStatus: 'confirmed',
    matchDate: '2026-11-04',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt', 'anlass'],
    priority: 2,
    shortDescription: 'Große Vorgeschichte: keine. Kurze Anreise, voller belgischer Gästeblock denkbar und das erste Pflichtspiel beider Klubs gegeneinander: reicht auch.',
    background: 'PSV und Club Brugge sind sich trotz jahrzehntelanger Europapokalteilnahmen bislang nur in Freundschafts- und Turnierspielen begegnet. Das erste Pflichtspiel kommt jetzt in Eindhoven.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-shakhtar-fenerbahce-2026-11-25',
    homeTeam: 'Shakhtar Donetsk',
    awayTeam: 'Fenerbahçe',
    country: 'England',
    region: 'europe',
    city: 'London',
    stadium: 'Stamford Bridge',
    dateStatus: 'confirmed',
    matchDate: '2026-11-25',
    kickoffTime: '20:00',
    categories: ['auswaertsfahrt', 'anlass', 'unter_dem_radar'],
    priority: 2,
    shortDescription: 'Ukrainischer Heimverein an der Stamford Bridge gegen Fenerbahçe: als Groundhopping-Konstellation schwer zu toppen. Dazu kommt eine große türkische Community in London.',
    background: 'Shakhtar trägt seine Champions-League-Heimspiele 2026/27 wegen des Krieges an der Stamford Bridge aus. Gegen Fenerbahçe entsteht damit eines der ungewöhnlichsten Heimspiele der Ligaphase.',
    confirmedInfo: 'Shakhtar bestätigt Stamford Bridge als Heimspielort. Anstoß ist um 20:00 Uhr Ortszeit in London.',
    editorialAssessment: 'Hopper-Empfehlung: 7/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, 'https://shakhtar.com/en/news/2026/august/29_news/29_ucl_fixtures/', 'https://shakhtar.com/en/news/2026/august/21_news/21_shakhtar_stamford_bridge/', articleUrl],
  },
  {
    _id: 'ucl-watch-psg-roma-2026-11-25',
    homeTeam: 'Paris Saint-Germain',
    awayTeam: 'AS Roma',
    country: 'Frankreich',
    region: 'europe',
    city: 'Paris',
    stadium: 'Parc des Princes',
    dateStatus: 'confirmed',
    matchDate: '2026-11-25',
    kickoffTime: '21:00',
    categories: ['fanszene'],
    priority: 1,
    shortDescription: 'Interessant über Bande: Teile der Pariser Szene sind eng mit Napoli und Juve Stabia verbunden. Gerade die Napoli-Freundschaft bringt für ein Spiel gegen Roma zusätzlichen Stoff.',
    background: 'PSG- und Napoli-Gruppen traten bei früheren Treffen gemeinsam auf; Freunde aus Napoli und Juve Stabia waren zuletzt auch bei Champions-League-Finals im Pariser Umfeld sichtbar.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-aek-galatasaray-2026-12-08',
    homeTeam: 'AEK Athen',
    awayTeam: 'Galatasaray',
    country: 'Griechenland',
    region: 'europe',
    city: 'Athen',
    stadium: 'ALLWYN Arena',
    dateStatus: 'confirmed',
    matchDate: '2026-12-08',
    kickoffTime: '22:00',
    categories: ['fanszene', 'anlass'],
    priority: 2,
    shortDescription: 'AEKs Identität ist eng mit Konstantinopel verbunden – nun kommt einer der größten Klubs des heutigen Istanbul nach Nea Filadelfeia. Historischer Kontext ja, erfundene Hassgeschichte nein.',
    background: 'AEK wurde 1924 von Griechen aus Konstantinopel gegründet. Eine gewachsene Fanfeindschaft zu Galatasaray ist daraus nicht automatisch abzuleiten; 2018 gab es sogar eine Solidaritätsbotschaft von Gala an Griechenland.',
    confirmedInfo: 'Termin ist bestätigt; 22:00 Uhr ist die Ortszeit in Athen.',
    editorialAssessment: 'Hopper-Empfehlung: 8,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, 'https://www.galatasaray.org/haber/futbol/sampiyonlar-ligi/galatasarayin-sampiyonlar-ligi-rakipleri-belli-oldu/60827', articleUrl],
  },
  {
    _id: 'ucl-tip-galatasaray-feyenoord-2027-01-19',
    homeTeam: 'Galatasaray',
    awayTeam: 'Feyenoord',
    country: 'Türkei',
    region: 'europe',
    city: 'Istanbul',
    stadium: 'RAMS Park',
    dateStatus: 'confirmed',
    matchDate: '2027-01-19',
    kickoffTime: '20:45',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 2,
    shortDescription: 'Keine belegte historische Feindschaft, dafür zwei große Anhängerschaften und ein Feyenoord-Anhang, der europäische Gästekontingente regelmäßig sehr ordentlich füllt.',
    background: 'Der Reiz liegt klar in der Kombination aus Galatasaray-Heimkurve und reisestarkem Feyenoord-Anhang. Mögliche Sanktionen gegen Feyenoord-Gästefans bleiben bis Januar im Blick.',
    confirmedInfo: 'Termin ist bestätigt; 20:45 Uhr ist die Ortszeit in Istanbul.',
    editorialAssessment: 'Hopper-Empfehlung: 7,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, 'https://www.galatasaray.org/haber/futbol/sampiyonlar-ligi/galatasarayin-sampiyonlar-ligi-rakipleri-belli-oldu/60827', articleUrl],
  },
  {
    _id: 'ucl-tip-aek-roma-2027-01-19',
    homeTeam: 'AEK Athen',
    awayTeam: 'AS Roma',
    country: 'Griechenland',
    region: 'europe',
    city: 'Athen',
    stadium: 'ALLWYN Arena',
    dateStatus: 'confirmed',
    matchDate: '2027-01-19',
    kickoffTime: '22:00',
    categories: ['fanszene', 'rivalitaet'],
    priority: 3,
    shortDescription: 'Alte Zaunfahnen-Geschichte, reale Zwischenfälle Anfang der 2000er und die heutige Roma-Freundschaft zu AEK-Rivale Panathinaikos. Unser Top-Tipp der Ligaphase.',
    background: '2002 gab es zwischen beiden Szenen eine Banner-Geschichte und beim Rückspiel in Rom Festnahmen und weitere Zwischenfälle. Heute kommt die enge Verbindung von Teilen der Roma-Szene zu Panathinaikos hinzu.',
    confirmedInfo: 'Termin ist bestätigt; 22:00 Uhr ist die Ortszeit in Athen.',
    editorialAssessment: 'Hopper-Empfehlung: 10/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-psv-stuttgart-2027-01-27',
    homeTeam: 'PSV Eindhoven',
    awayTeam: 'VfB Stuttgart',
    country: 'Niederlande',
    region: 'europe',
    city: 'Eindhoven',
    stadium: 'Philips Stadion',
    dateStatus: 'confirmed',
    matchDate: '2027-01-27',
    kickoffTime: '21:00',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 2,
    shortDescription: 'Kurze Strecke, hohe Stuttgarter Nachfrage – und nach den Ereignissen von Deventer 2025 auch die niederländischen Behörden als zusätzlicher Faktor.',
    background: 'Die PSV-Szene gilt im niederländischen Vergleich eher als entspannter. Spannend ist auch die Behördenebene: Beim VfB-Gastspiel in Deventer 2025 gab es einen massiven Polizeieinsatz und später unterschiedliche Bewertungen von Verein und Behörden.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 8,5/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-tip-psg-galatasaray-2027-01-27',
    homeTeam: 'Paris Saint-Germain',
    awayTeam: 'Galatasaray',
    country: 'Frankreich',
    region: 'europe',
    city: 'Paris',
    stadium: 'Parc des Princes',
    dateStatus: 'confirmed',
    matchDate: '2027-01-27',
    kickoffTime: '21:00',
    categories: ['fanszene', 'rivalitaet', 'auswaertsfahrt'],
    priority: 3,
    shortDescription: 'Schwere Ausschreitungen 2001, erneute Vorfälle 2019 und eine große Galatasaray-Diaspora in Westeuropa. Eines der am besten belegten Risikospiele der Auslosung.',
    background: '2001 wurde PSG – Galatasaray nach schweren Ausschreitungen lange unterbrochen. Auch 2019 kam es vor dem Spiel zu Auseinandersetzungen; damals ging ein großer Teil der Gala-Gästetickets an Fans aus Deutschland.',
    confirmedInfo: 'Termin und Anstoßzeit sind von der UEFA bestätigt.',
    editorialAssessment: 'Hopper-Empfehlung: 10/10.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
  {
    _id: 'ucl-watch-liverpool-lens-2027-01-27',
    homeTeam: 'Liverpool',
    awayTeam: 'RC Lens',
    country: 'England',
    region: 'europe',
    city: 'Liverpool',
    stadium: 'Anfield',
    dateStatus: 'confirmed',
    matchDate: '2027-01-27',
    kickoffTime: '20:00',
    categories: ['fanszene', 'auswaertsfahrt'],
    priority: 1,
    shortDescription: 'Lens dürfte auch für Liverpool ordentlich mobilisieren. Der Gästeblock ist hier der spannendste Teil; der übliche Champions-League-Touristenanteil rund um Anfield drückt die Empfehlung etwas.',
    background: 'Lens hat bei früheren Europapokalreisen auch weite Strecken mit starken Gästekontingenten bewältigt. Deshalb bleibt Anfield trotz Hochglanzfaktor auf der Beobachtungsliste.',
    confirmedInfo: 'Termin ist bestätigt; 20:00 Uhr ist die Ortszeit in Liverpool.',
    editorialAssessment: 'Beobachtungsliste.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-09-02',
    article,
    sourceUrls: [uefaFixtures, articleUrl],
  },
]
