const championsLeagueSource = 'https://www.uefa.com/uefachampionsleague/news/02a6-20d57cfcd03e-407c22a7f465-1000--2026-27-champions-league-teams-dates-draws-format-final/'

function uclPhase(id, phase, startDate, endDate = startDate, note) {
  return {
    _id: `starter-competition-ucl-${id}`,
    name: 'UEFA Champions League',
    shortName: 'CHAMPIONS LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase,
    startDate,
    endDate,
    status: 'confirmed',
    ...(note ? {note} : {}),
    sourceUrls: [championsLeagueSource],
  }
}

export const starterCompetitions = [
  uclPhase('md1-2026', 'Ligaphase · Spieltag 1', '2026-09-08', '2026-09-10'),
  uclPhase('md2-2026', 'Ligaphase · Spieltag 2', '2026-10-13', '2026-10-14'),
  uclPhase('md3-2026', 'Ligaphase · Spieltag 3', '2026-10-20', '2026-10-21'),
  uclPhase('md4-2026', 'Ligaphase · Spieltag 4', '2026-11-03', '2026-11-04'),
  uclPhase('md5-2026', 'Ligaphase · Spieltag 5', '2026-11-24', '2026-11-25'),
  uclPhase('md6-2026', 'Ligaphase · Spieltag 6', '2026-12-08', '2026-12-09'),
  uclPhase('md7-2027', 'Ligaphase · Spieltag 7', '2027-01-19', '2027-01-20'),
  uclPhase('md8-2027', 'Ligaphase · Spieltag 8', '2027-01-27'),
  uclPhase('playoffs-first-2027', 'K.-o.-Playoffs · Hinspiele', '2027-02-16', '2027-02-17'),
  uclPhase('playoffs-second-2027', 'K.-o.-Playoffs · Rückspiele', '2027-02-23', '2027-02-24'),
  uclPhase('r16-first-2027', 'Achtelfinale · Hinspiele', '2027-03-09', '2027-03-10'),
  uclPhase('r16-second-2027', 'Achtelfinale · Rückspiele', '2027-03-16', '2027-03-17'),
  uclPhase('qf-first-2027', 'Viertelfinale · Hinspiele', '2027-04-06', '2027-04-07'),
  uclPhase('qf-second-2027', 'Viertelfinale · Rückspiele', '2027-04-13', '2027-04-14'),
  uclPhase('sf-first-2027', 'Halbfinale · Hinspiele', '2027-04-27', '2027-04-28'),
  uclPhase('sf-second-2027', 'Halbfinale · Rückspiele', '2027-05-04', '2027-05-05'),
  uclPhase('final-2027', 'Finale', '2027-06-05', '2027-06-05', 'Finale im Estadio Metropolitano in Madrid.'),
  {
    _id: 'starter-competition-uel-md1-2026',
    name: 'UEFA Europa League',
    shortName: 'EUROPA LEAGUE',
    region: 'europe',
    competitionType: 'continental_club',
    phase: 'Ligaphase · Spieltag 1',
    startDate: '2026-09-16',
    endDate: '2026-09-17',
    status: 'confirmed',
    note: 'Erster Spieltag der Ligaphase 2026/27.',
    sourceUrls: [
      'https://www.uefa.com/uefaeuropaleague/news/02a8-2174cafa5bb6-82bbc20c9b92-1000--2026-27-europa-league-all-the-league-phase-fixtures/',
    ],
  },
]

export const starterMatches = [
  {
    _id: 'starter-match-hibernian-hearts-2026-09-03',
    homeTeam: 'Hibernian',
    awayTeam: 'Heart of Midlothian',
    country: 'Schottland',
    region: 'europe',
    city: 'Edinburgh',
    stadium: 'Easter Road',
    dateStatus: 'confirmed',
    matchDate: '2026-09-03',
    kickoffTime: '19:45',
    categories: ['rivalitaet', 'fanszene'],
    priority: 3,
    shortDescription: 'Erstes Edinburgh Derby der Saison – und der Hearts-Gästebereich ist bereits ausverkauft. Ein Termin, bei dem das Drumherum den Platz im Kalender ziemlich problemlos rechtfertigt.',
    awayFans: 'allowed',
    ticketSituation: 'difficult',
    lastChecked: '2026-08-31',
    sourceUrls: [
      'https://www.heartsfc.co.uk/blogs/news/ticket-information-hibernian-a-3',
      'https://www.heartsfc.co.uk/pages/first-team-fixtures?type=fixtures',
    ],
  },
  {
    _id: 'starter-match-dinamo-fcsb-2026-09-05',
    homeTeam: 'Dinamo București',
    awayTeam: 'FCSB',
    country: 'Rumänien',
    region: 'europe',
    city: 'Bukarest',
    stadium: 'Stadionul Arcul de Triumf',
    dateStatus: 'confirmed',
    matchDate: '2026-09-05',
    kickoffTime: '20:30',
    categories: ['rivalitaet', 'fanszene', 'anlass'],
    priority: 3,
    shortDescription: 'Das Derby de România landet diesmal im nur rund 8.000 Plätze großen Arcul de Triumf, weil die Arena Națională nicht verfügbar ist. Eine geplante Verlegung nach Cluj scheiterte am Widerstand von Dinamo-Fans.',
    awayFans: 'unclear',
    ticketSituation: 'difficult',
    lastChecked: '2026-08-31',
    sourceUrls: [
      'https://dinamo1948.ro/regulament-campanie-de-bilete-dinamo-fcsb/',
      'https://www.digisport.ro/amphtml/fotbal/liga-1/gata-s-a-stabilit-unde-se-joaca-dinamo-fcsb-4443005',
    ],
  },
  {
    _id: 'starter-match-sporting-galatasaray-2026-09-09',
    homeTeam: 'Sporting CP',
    awayTeam: 'Galatasaray',
    country: 'Portugal',
    region: 'europe',
    city: 'Lissabon',
    stadium: 'Estádio José Alvalade',
    dateStatus: 'confirmed',
    matchDate: '2026-09-09',
    kickoffTime: '20:00',
    categories: ['fanszene'],
    priority: 2,
    shortDescription: 'Sporting startet die Champions-League-Saison zuhause gegen Galatasaray. Aus Fanszene-Sicht eine der interessanteren Paarungen des ersten Spieltags; konkrete Gästefan- und Ticketdetails beobachten wir noch.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-08-31',
    sourceUrls: [
      'https://www.sporting.pt/pt/noticias/futebol/equipa-principal/2026-08-29/uefa-champions-league-o-calendario-da-fase-de-liga',
      'https://www.galatasaray.org/haber/futbol/sampiyonlar-ligi/sampiyonlar-ligi-fiksturumuz-belli-oldu/60836',
    ],
  },
  {
    _id: 'starter-match-rangers-celtic-2026-09-13',
    homeTeam: 'Rangers',
    awayTeam: 'Celtic',
    country: 'Schottland',
    region: 'europe',
    city: 'Glasgow',
    stadium: 'Ibrox Stadium',
    dateStatus: 'confirmed',
    matchDate: '2026-09-13',
    kickoffTime: '12:00',
    categories: ['rivalitaet', 'fanszene', 'anlass'],
    priority: 3,
    shortDescription: 'Old Firm im Viertelfinale des Premier Sports Cup. Rangers hat die Celtic-Auswärtsquote auf nur 300 Tickets begrenzt – eine zusätzliche Besonderheit bei einer ohnehin außergewöhnlichen Paarung.',
    awayFans: 'allowed',
    ticketSituation: 'difficult',
    lastChecked: '2026-08-31',
    sourceUrls: [
      'https://www.rangers.co.uk/article/fixture-update-premier-sports-cup-quarter-final/442yAazOFNReiaNW3WIUMT',
      'https://www.rangers.co.uk/article/club-statement-280826/2yo8vwavXQH3bogelAXocq',
    ],
  },
  {
    _id: 'starter-match-juventus-nec-2026-09-17',
    homeTeam: 'Juventus',
    awayTeam: 'N.E.C.',
    country: 'Italien',
    region: 'europe',
    city: 'Turin',
    stadium: 'Allianz Stadium',
    dateStatus: 'confirmed',
    matchDate: '2026-09-17',
    kickoffTime: '21:00',
    categories: ['auswaertsfahrt', 'anlass'],
    priority: 2,
    shortDescription: 'N.E.C. eröffnet seine Europa-League-Ligaphase direkt bei Juventus. Für Nijmegen eine außergewöhnliche Auswärtsreise; konkrete Ticketinformationen des Vereins stehen aktuell noch aus.',
    awayFans: 'unclear',
    ticketSituation: 'unknown',
    lastChecked: '2026-08-31',
    sourceUrls: [
      'https://www.nec-nijmegen.nl/nieuws/nieuws/uefa-europa-league-schema-bekend-n.e.c.-opent-in-turijn.htm',
      'https://www.uefa.com/uefaeuropaleague/news/02a8-2174cafa5bb6-82bbc20c9b92-1000--2026-27-europa-league-all-the-league-phase-fixtures/',
    ],
  },
]
